SELECT acc.COLUMN_NAME AS column_name
FROM ALL_CONSTRAINTS ac
JOIN ALL_CONS_COLUMNS acc
  ON ac.OWNER = acc.OWNER
 AND ac.CONSTRAINT_NAME = acc.CONSTRAINT_NAME
WHERE ac.OWNER = '{{schema}}'
  AND ac.TABLE_NAME = '{{tableName}}'
  AND ac.CONSTRAINT_TYPE = 'P'
ORDER BY acc.POSITION
