SELECT K.COLUMN_NAME AS column_name
FROM QSYS2.SYSKEYCST K
JOIN QSYS2.SYSCST C
  ON C.CONSTRAINT_SCHEMA = K.CONSTRAINT_SCHEMA
 AND C.CONSTRAINT_NAME = K.CONSTRAINT_NAME
 AND C.TABLE_SCHEMA = K.TABLE_SCHEMA
 AND C.TABLE_NAME = K.TABLE_NAME
WHERE K.TABLE_SCHEMA = '{{schema}}'
  AND K.TABLE_NAME = '{{tableName}}'
  AND C.CONSTRAINT_TYPE = 'PRIMARY KEY'
ORDER BY K.ORDINAL_POSITION
