SELECT COLUMN_NAME AS column_name,
  DATA_TYPE AS data_type,
  LENGTH AS length,
  NUMERIC_SCALE AS scale
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = '{{schema}}'
  AND TABLE_NAME IN ({{tables}})
ORDER BY TABLE_NAME, ORDINAL_POSITION;