SELECT c.COLUMN_NAME AS column_name
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE c
  ON tc.CONSTRAINT_NAME = c.CONSTRAINT_NAME
 AND tc.TABLE_SCHEMA = c.TABLE_SCHEMA
 AND tc.TABLE_NAME = c.TABLE_NAME
WHERE tc.TABLE_SCHEMA = '{{schema}}'
  AND tc.TABLE_NAME = '{{tableName}}'
  AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
ORDER BY c.ORDINAL_POSITION
