export const CURRENT_RELEASE = {
  version: "1.2.2",
  date: "2026-09-28",
  title: "Analítica, comparación y claves locales",
  changes: [
    "Panel de Actividad con uso por periodo, sesiones, páginas, operaciones, errores y recurrencia por usuario.",
    "Historial de actividad con búsqueda, filtros y paginación en servidor.",
    "PK del diccionario local visibles de forma consistente en Schema, Volumen y Fila a fila, sin depender del esquema.",
    "Listado de diccionarios con PK visible y encabezado fijo sin desplazamiento horizontal.",
    "Restauración del filtro, página, tamaño de página y selección de tablas al volver desde las diferencias.",
    "Script para actualizar las PK locales desde az7dbkeys.csv y usar todas las columnas como clave cuando una tabla no está definida en el archivo.",
    "Administración de perfiles con permisos por módulo y acción: View, New, Edit, Delete y Save.",
    "Perfiles predeterminados admin y solo lectura, con asignación desde la opción Usuarios.",
    "Registro automático de usuarios autenticados y edición de sus datos locales.",
    "Persistencia de catálogos con nombre asignado, DSN y esquemas de búsqueda.",
    "Carga de diccionarios por nombre lógico de catálogo y selección de origen y destino.",
    "Comparación de esquema, volumen y filas entre entornos con resolución de DSN físico.",
    "Corrección de assets y fallback SPA para despliegues bajo /deltacore/ en IBM i.",
    "Asignación exclusiva de un perfil por usuario y menú filtrado por permisos.",
    "Logout local determinista y validación de acceso para usuarios de solo lectura.",
    "Conexión IBM i mediante la configuración ODBC del sistema y diagnósticos SQL/ODBC en backend.",
    "Carga de diccionarios guardados por DSN y tabla, sin consultas automáticas al escribir.",
    "Mensajes informativos visibles durante cinco segundos y arranque PM2 compatible con Node en IBM i.",
  ],
} as const;